{{-- filepath: resources/views/exports/traffic-trend-report.blade.php --}}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Traffic Trend Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
        }

        .title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .data {
            margin-bottom: 8px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #333;
            padding: 4px;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="title">Traffic Trend Report ({{ ucfirst($filter) }})</div>
    <div class="data">
        <p>Generated by Zabbix Monitoring System</p>
        <p>Date: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
    <div class="data">Range: {{ $trendData['from'] ?? '-' }} - {{ $trendData['till'] ?? '-' }}</div>
    <div class="data">
        <div>Min Inbound: <b>{{ number_format($trendData['minValueIn'] ?? 0, 2) }} mbps</b></div>
        <div>Max Inbound: <b>{{ number_format($trendData['maxValueIn'] ?? 0, 2) }} mbps</b></div>
        <div>Avg Inbound: <b>{{ number_format($trendData['avgValueIn'] ?? 0, 2) }} mbps</b></div>
        <div>Min Outbound: <b>{{ number_format($trendData['minValueOut'] ?? 0, 2) }} mbps</b></div>
        <div>Max Outbound: <b>{{ number_format($trendData['maxValueOut'] ?? 0, 2) }} mbps</b></div>
        <div>Avg Outbound: <b>{{ number_format($trendData['avgValueOut'] ?? 0, 2) }} mbps</b></div>
    </div>


    <div class="data">
        <canvas id="trafficChart" height="80"></canvas>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                const ctx = document.getElementById('trafficChart').getContext('2d');
                if (window['trafficChartInstance']) {
                    window['trafficChartInstance'].destroy();
                }

                window['trafficChartInstance'] = new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: @json($labels),
                        datasets: [{
                                label: 'Inbound Traffic (MB)',
                                data: @json($dataIn),
                                borderColor: '#4CAF50',
                                backgroundColor: 'rgba(76, 175, 80, 0.1)',
                                tension: 0.5,
                                yAxisID: 'y',
                            },
                            {
                                label: 'Outbound Traffic (MB)',
                                data: @json($dataOut),
                                borderColor: '#FF9800',
                                backgroundColor: 'rgba(255, 152, 0, 0.1)',
                                tension: 0.5,
                                yAxisID: 'y1',
                            }
                        ]
                    },
                    options: {
                        responsive: true,
                        scales: {
                            y: {
                                beginAtZero: true,
                                title: {
                                    display: true,
                                    text: 'Traffic (MB)'
                                }
                            },
                            y1: {
                                beginAtZero: true,
                                position: 'right',
                                title: {
                                    display: true,
                                    text: 'Traffic (MB)'
                                }
                            }
                            x: {
                                ticks: {
                                    autoSkip: false
                                }
                            }
                        }
                    }
                });
            });
        </script>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <hr>

    <h3>Traffic Data</h3>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Inbound Traffic (MB)</th>
                <th>Outbound Traffic (MB)</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($labels as $index => $date)
                <tr>
                    <td>{{ $date }}</td>
                    <td>{{ number_format($dataIn[$index] ?? 0, 2) }}</td>
                    <td>{{ number_format($dataOut[$index] ?? 0, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>


</body>

</html>
